### ISSUE TITLE
first number get cut of

### ISSUE THREAD

**Issue by SunboX** [joushx/jQuery.EAN13#27]
if I set the option `number: true`, the first number (char) is missing in the generated barcode. (seems that it is placed outside the canvas)

**Comment by joushx** [comment]
Which number and options did you use? I could not reproduce the problem with the example from the readme file. http://jsfiddle.net/56phmh6L/

**Comment by SunboX** [comment]
## Code

```html
<canvas id="ean" width="200" height="100"></canvas>
```

```js
jQuery('#ean').EAN13('1230000000321', {
    number: true,
    prefix: false
});
```

## Output
![ean](https://cloud.githubusercontent.com/assets/83344/11805153/cd327628-a309-11e5-9e90-f1ef5eb7184d.png)

The first digit, the `1`, is missing in the output.

**Comment by SunboX** [comment]
Btw., I'm using Firefox Developer Edition 44.0a2 (2015-12-13)

**Comment by joushx** [comment]
It's not a bug, it's a feature. 

The prefix option controls the display if this digit: http://jsfiddle.net/56phmh6L/3/

**Comment by SunboX** [comment]
Ah, I understand. I thought I could append a prefix with this option. Thought the wrong way, sorry for that. :+1:
