### ISSUE TITLE
Adding padding destroys the generated barcode

### ISSUE THREAD

**Issue by SunboX** [joushx/jQuery.EAN13#28]
Adding `padding` destroys the generated barcode.
I'm using Firefox Developer Edition 44.0a2 (2015-12-13)

## Code

```html
<canvas id="ean" width="220" height="120"></canvas>
```

```js
jQuery('#ean').EAN13('1230000000338', {
    number: true,
    prefix: false,
    background: '#ffffff',
    padding: '10'
});
```

## Output
![ean](https://cloud.githubusercontent.com/assets/83344/11806835/0dfa3f86-a316-11e5-99e3-4b2211c7ef4e.png)

## Output without `padding`
![ean2](https://cloud.githubusercontent.com/assets/83344/11806892/592405dc-a316-11e5-8288-a0b180553116.png)

**Comment by joushx** [comment]
Please have a look at the readme file. The padding option needs an integer. 

```js
jQuery('#ean').EAN13('1230000000338', {
    number: true,
    prefix: false,
    background: '#ffffff',
    padding: 10
});
```

**Comment by SunboX** [comment]
oh, sry again. :cry: Maybe adding a `parseInt(padding, 10)` to avoid such misreadings?

**Comment by joushx** [comment]
In my opinion the user has to make sure the parameters are correct. It would blow up the code to check for all possible wrong use cases.

**Comment by SunboX** [comment]
k, sry again
