### ISSUE TITLE
plz re-add `dist` folder

### ISSUE THREAD

**Issue by SunboX** [joushx/jQuery.EAN13#34]
Could you please consider re-adding the `dist` folder? I'm using Bower to fetch always the latest version of jQuery.EAN13. Without the dist folder it get's really difficult.

**Comment by joushx** [comment]
I think it is some kind of ugly to have the compiled code checked into the version control. Also even some authors of Bower [consider deprecating it](https://github.com/bower/bower/issues/2298). 

I would recomment to switch to npm as a package manager. By using it, you automatically get the latest builds as you would with bower and the dist folder.

I now switched from Grunt to only use npm and published the code also to npmjs.com so you don't have to build it every time. Simply use `npm install jquery-ean13` to get it.

I hope this solution works for you.

**Comment by gustavi** [comment]
Some people doesnt want this s*** of npm and just a simple raw file.

**Comment by joushx** [comment]
[jquery](https://github.com/jquery/jquery) does it. And [react](https://github.com/facebook/react). And [angular](https://github.com/angular/angular.js). However, [tree.js](https://github.com/mrdoob/three.js/tree/dev/build) does not do it.

You may download the compiled files always from the release section without using npm. I would also recommend this as the compability between releases is not guaranteed when you hotlink the library.
