### ISSUE TITLE
Barcode showing without number in pdf despite the options number se set to true

### ISSUE THREAD

**Issue by nabendu23** [joushx/jQuery.EAN13#40]
Hi @joushx ,

I am generating the barcode in javascript and directly printing it into pdf file. The image is generating the barcode but without the EAN  code number.

Can you please urgently advice? Here is my code snippet and output

```js
var canvas = document.createElement('canvas');

canvas.id = id;
canvas.setAttribute("height","16px");
var options = {
number: true,
prefix: true
};
new EAN13(canvas, EANCode, options);                                            
var imgDataConfirm = canvas.toDataURL("image/png", 1.0);
doc.addImage(imgDataConfirm, 'PNG', 80 * j, 265 + 30 * i, 60, 20);
```

![image](https://user-images.githubusercontent.com/22400621/90164467-55eeda00-dd8f-11ea-83a3-f05521022059.png)

**Comment by joushx** [comment]
It works for me in a browser and I see the number in the PNG output. You may see this example: https://jsfiddle.net/zL13r2ew/

This looks like a problem with the PDF file or viewer.

**Comment by nabendu23** [comment]
Thanks very much @joushx . I was not rendering the canvas due to which the number was not showing. It's now reoslved. Thank you :) .
